Repository fixplzz/fixplz-BE, pull requests merged in 2023-11, with the labels that each got.

#32 [FEATURE] - [STAT] 일일 방문자 기능 구현
  src/main/java/com/fixplz/stat/application/controller/VisitorController.java
  src/main/java/com/fixplz/stat/application/dto/response/VisitorResponse.java
  src/main/java/com/fixplz/stat/application/service/VisitorService.java
  src/main/java/com/fixplz/stat/domain/aggregate/KeyFactory.java
  src/main/java/com/fixplz/stat/domain/aggregate/entity/Visitor.java
  src/main/java/com/fixplz/stat/domain/aggregate/vo/Test.java
  src/main/java/com/fixplz/stat/domain/aggregate/vo/VisitorKey.java
  src/main/java/com/fixplz/stat/domain/repository/VisitorDomainRepository.java
  src/main/resources/db/data/data.sql
  src/test/java/com/fixplz/stat/application/service/VisitorServiceTests.java
Labels: 📬 API, 🔨 Refactor, 🎯 Test, ✨ Feature

#38 feature : 민원 entity, 기본 클래스 생성
  src/main/java/com/fixplz/complaint/application/controller/ComplaintController.java
  src/main/java/com/fixplz/complaint/application/controller/Test.java
  src/main/java/com/fixplz/complaint/application/dto/request/CreateComplaintRequest.java
  src/main/java/com/fixplz/complaint/application/dto/request/Test.java
  src/main/java/com/fixplz/complaint/application/dto/response/CreateComplaintResponse.java
  src/main/java/com/fixplz/complaint/application/dto/response/Test.java
  src/main/java/com/fixplz/complaint/application/service/ComplaintService.java
  src/main/java/com/fixplz/complaint/application/service/Test.java
  src/main/java/com/fixplz/complaint/domain/aggregate/entity/Complaint.java
  src/main/java/com/fixplz/complaint/domain/aggregate/entity/Test.java
  src/main/java/com/fixplz/complaint/domain/aggregate/vo/FacilityNoVO.java
  src/main/java/com/fixplz/complaint/domain/aggregate/vo/FilterCategory.java
  src/main/java/com/fixplz/complaint/domain/aggregate/vo/FilterCategoryConverter.java
  src/main/java/com/fixplz/complaint/domain/aggregate/vo/ProcessingStatus.java
  src/main/java/com/fixplz/complaint/domain/aggregate/vo/ProcessingStatusConverter.java
  src/main/java/com/fixplz/complaint/domain/aggregate/vo/Test.java
  src/main/java/com/fixplz/complaint/domain/repository/ComplaintRepository.java
  src/main/java/com/fixplz/complaint/domain/repository/Test.java
  src/main/java/com/fixplz/complaint/domain/service/ComplaintDomainService.java
  src/main/java/com/fixplz/complaint/domain/service/Test.java
  src/main/java/com/fixplz/complaint/infra/service/ComplaintInfraService.java
  src/main/java/com/fixplz/complaint/infra/service/Test.java
  src/test/java/com/fixplz/complaint/service/ComplaintServiceTests.java
Labels: ✨ Feature

#36 [FEATURE] - [ADMIN] 관리자 등록 / 로그인 기능 구현
  build.gradle
  src/main/java/com/fixplz/Admin/application/controller/AdminController.java
  src/main/java/com/fixplz/Admin/application/dto/request/Test.java
  src/main/java/com/fixplz/Admin/application/dto/response/LoginResponse.java
  src/main/java/com/fixplz/Admin/application/dto/response/Test.java
  src/main/java/com/fixplz/Admin/application/service/AdminService.java
  src/main/java/com/fixplz/Admin/application/service/Test.java
  src/main/java/com/fixplz/Admin/domain/aggregate/entity/Admin.java
  src/main/java/com/fixplz/Admin/domain/repository/AdminRepository.java
  src/main/java/com/fixplz/Admin/domain/service/AdminService.java
  src/main/java/com/fixplz/Admin/infra/service/Test.java
  src/main/java/com/fixplz/admin/application/dto/request/AdminRequest.java
  src/main/java/com/fixplz/admin/application/dto/response/AdminResponse.java
  src/main/java/com/fixplz/admin/domain/aggregate/entity/Admin.java
  src/main/java/com/fixplz/admin/domain/aggregate/entity/Role.java
  src/main/java/com/fixplz/admin/infra/service/Test.java
  src/main/java/com/fixplz/auth/CustomAuthenticationFilter.java
  src/main/java/com/fixplz/auth/Jwt401Handler.java
  src/main/java/com/fixplz/auth/Jwt403Handler.java
  src/main/java/com/fixplz/auth/JwtTokenProvider.java
  src/main/java/com/fixplz/common/response/ApiResponse.java
  src/main/java/com/fixplz/configuration/CorsConfig.java
  src/main/java/com/fixplz/configuration/JwtSecurityConfig.java
  src/main/java/com/fixplz/configuration/SecurityConfig.java
Labels: ✨ Feature

#45 Refactor: 시설물 엔티티 카테고리 enum 단일화
  src/main/java/com/fixplz/facility/domain/aggregate/entity/Facility.java
  src/main/java/com/fixplz/facility/domain/aggregate/entity/enumtype/FacilityCategory.java
Labels: 🔨 Refactor

#49 [Feature]-{FACILITY} 시설물 생성 및 QR 이미지 생성 기능 구현
  build.gradle
  src/main/java/com/fixplz/admin/application/controller/AdminController.java
  src/main/java/com/fixplz/admin/application/dto/response/LoginResponse.java
  src/main/java/com/fixplz/admin/application/service/AdminService.java
  src/main/java/com/fixplz/admin/domain/aggregate/entity/Admin.java
  src/main/java/com/fixplz/admin/domain/repository/AdminRepository.java
  src/main/java/com/fixplz/configuration/SecurityConfig.java
  src/main/java/com/fixplz/facility/application/controller/FacilityController.java
  src/main/java/com/fixplz/facility/application/dto/request/FacilityRequest.java
  src/main/java/com/fixplz/facility/application/dto/request/Test.java
  src/main/java/com/fixplz/facility/application/dto/response/FacilityResponse.java
  src/main/java/com/fixplz/facility/application/dto/response/Test.java
  src/main/java/com/fixplz/facility/application/service/FacilityService.java
  src/main/java/com/fixplz/facility/domain/aggregate/entity/Facility.java
  src/main/java/com/fixplz/facility/domain/aggregate/entity/enumtype/FacilityCategory.java
  src/main/java/com/fixplz/facility/domain/aggregate/enumtype/Department.java
  src/main/java/com/fixplz/facility/domain/aggregate/enumtype/FacilityCategory.java
  src/main/java/com/fixplz/facility/domain/repository/FacilityRepository.java
  src/main/java/com/fixplz/facility/domain/service/QRApiDomainService.java
  src/main/java/com/fixplz/facility/infra/service/FacilityInfraService.java
  src/main/java/com/fixplz/facility/infra/service/QRApiInfraService.java
  src/main/java/com/fixplz/image/application/controller/Test.java
  src/main/java/com/fixplz/image/application/dto/request/Test.java
  src/main/java/com/fixplz/image/application/dto/response/Test.java
  src/main/java/com/fixplz/image/application/service/Test.java
  src/main/java/com/fixplz/image/domain/aggregate/entity/Test.java
  src/main/java/com/fixplz/image/domain/aggregate/vo/Test.java
  src/main/java/com/fixplz/image/domain/repository/Test.java
  src/main/java/com/fixplz/image/domain/service/Test.java
  src/main/java/com/fixplz/image/infra/service/Test.java
  src/main/java/com/fixplz/like/application/controller/LikeController.java
  src/main/java/com/fixplz/like/application/dto/request/Test.java
  src/main/java/com/fixplz/like/application/dto/response/Test.java
  src/main/java/com/fixplz/like/application/service/LikeService.java
  src/main/java/com/fixplz/like/domain/aggregate/entity/Like.java
  src/main/java/com/fixplz/like/domain/aggregate/vo/LikeVO.java
  src/main/java/com/fixplz/like/domain/repository/LikeRepository.java
  src/main/java/com/fixplz/like/domain/service/LikeDomainSerivce.java
  src/main/java/com/fixplz/like/infra/service/Test.java
  src/main/java/com/fixplz/reply/application/controller/ReplyController.java
  src/main/java/com/fixplz/reply/application/dto/request/Test.java
  src/main/java/com/fixplz/reply/application/dto/response/Test.java
  src/main/java/com/fixplz/reply/application/service/ReplyService.java
  src/main/java/com/fixplz/reply/domain/aggregate/entity/Reply.java
  src/main/java/com/fixplz/reply/domain/aggregate/vo/PostNoVO.java
  src/main/java/com/fixplz/reply/domain/repository/ReplyRepository.java
  src/main/java/com/fixplz/reply/domain/service/ReplyDomainService.java
  src/main/java/com/fixplz/reply/infra/service/Test.java
Labels: 🔨 Refactor, ✨ Feature

#50 [Feature] - {FACILITY} QR 사진 S3 업로드 기능 구현 및 DB 반영
  build.gradle
  src/main/java/com/fixplz/FixplzApplication.java
  src/main/java/com/fixplz/common/handler/ExceptionResponseHandler.java
  src/main/java/com/fixplz/common/utils/S3Storage.java
  src/main/java/com/fixplz/common/utils/dto/response/S3StrorageResponse.java
  src/main/java/com/fixplz/configuration/AmazonS3Config.java
  src/main/java/com/fixplz/facility/application/controller/FacilityController.java
  src/main/java/com/fixplz/facility/application/service/FacilityService.java
  src/main/java/com/fixplz/facility/domain/aggregate/entity/Facility.java
  src/main/java/com/fixplz/facility/domain/service/QRApiDomainService.java
  src/main/java/com/fixplz/facility/infra/service/QRApiInfraService.java
Labels: 📬 API, ✨ Feature

#52 [Feature] - {FACILITY} 시설물 crud 기능 구현
  build.gradle
  src/main/java/com/fixplz/common/handler/ExceptionResponseHandler.java
  src/main/java/com/fixplz/common/handler/exception/NoSuchDataException.java
  src/main/java/com/fixplz/facility/application/controller/FacilityController.java
  src/main/java/com/fixplz/facility/application/dto/request/FacilityDeleteRequest.java
  src/main/java/com/fixplz/facility/application/dto/request/FacilityRequest.java
  src/main/java/com/fixplz/facility/application/dto/response/FacilityResponse.java
  src/main/java/com/fixplz/facility/application/service/FacilityService.java
  src/main/java/com/fixplz/facility/domain/aggregate/entity/Facility.java
  src/main/java/com/fixplz/facility/domain/repository/FacilityRepository.java
Labels: 📬 API, ✨ Feature

#55 [Feature] - {Complaint} 신고 시 휴대폰인증 구현
  build.gradle
  src/main/java/com/fixplz/complaint/application/controller/ComplaintController.java
  src/main/java/com/fixplz/complaint/application/dto/request/SendSMSRequest.java
  src/main/java/com/fixplz/complaint/application/dto/request/ValidateSMSRequest.java
  src/main/java/com/fixplz/complaint/infra/service/MessageService.java
  src/main/java/com/fixplz/complaint/infra/service/RedisService.java
  src/main/java/com/fixplz/configuration/RedisConfig.java
  src/main/java/com/fixplz/configuration/SecurityConfig.java
Labels: ✨ Feature

#56 [Feature] - {Complaint} 민원 CRUD 기능 구현, 테스트 코드
  src/main/java/com/fixplz/complaint/application/controller/ComplaintController.java
  src/main/java/com/fixplz/complaint/application/dto/request/CreateComplaintRequest.java
  src/main/java/com/fixplz/complaint/application/dto/request/UpdateProcessingStatusRequest.java
  src/main/java/com/fixplz/complaint/application/dto/response/CreateComplaintResponse.java
  src/main/java/com/fixplz/complaint/application/dto/response/GetComplaintListResponse.java
  src/main/java/com/fixplz/complaint/application/dto/response/GetComplaintPageInfo.java
  src/main/java/com/fixplz/complaint/application/dto/response/GetComplaintResponse.java
  src/main/java/com/fixplz/complaint/application/dto/response/GetFacilityInfo.java
  src/main/java/com/fixplz/complaint/application/dto/response/UpdateProcessingStatusResponse.java
  src/main/java/com/fixplz/complaint/application/service/ComplaintService.java
  src/main/java/com/fixplz/complaint/domain/aggregate/entity/Complaint.java
  src/main/java/com/fixplz/complaint/domain/aggregate/vo/FilterCategory.java
  src/main/java/com/fixplz/complaint/domain/aggregate/vo/FilterCategoryConverter.java
  src/main/java/com/fixplz/complaint/domain/aggregate/vo/ProcessingStatus.java
  src/main/java/com/fixplz/complaint/domain/aggregate/vo/ProcessingStatusConverter.java
  src/main/java/com/fixplz/complaint/domain/repository/ComplaintRepository.java
  src/main/java/com/fixplz/complaint/infra/service/ComplaintInfraService.java
  src/main/java/com/fixplz/facility/infra/service/QRApiInfraService.java
  src/main/resources/db/data/data.sql
  src/test/java/com/fixplz/complaint/application/service/ComplaintServiceTests.java
  src/test/java/com/fixplz/complaint/service/ComplaintServiceTests.java
Labels: 🎯 Test, ✨ Feature

#58 feature : #57 민원 생성 이미지 추가
  src/main/java/com/fixplz/complaint/application/controller/ComplaintController.java
  src/main/java/com/fixplz/complaint/application/dto/request/CreateComplaintRequest.java
  src/main/java/com/fixplz/complaint/application/dto/response/GetComplaintResponse.java
  src/main/java/com/fixplz/complaint/application/service/ComplaintService.java
  src/main/java/com/fixplz/complaint/infra/service/ComplaintInfraService.java
  src/main/java/com/fixplz/complaint/infra/service/S3Service.java
  src/test/java/com/fixplz/complaint/application/service/ComplaintServiceTests.java
Labels: ✨ Feature
