Repository fixplzz/fixplz-BE, pull requests merged in 2023-10, with the labels that each got.

#6 feature : #3 답변 entity, 기본 클래스 생성
  src/main/java/com/fixplz/common/response/ApiResponse.java
  src/main/java/com/fixplz/reply/application/controller/ReplyController.java
  src/main/java/com/fixplz/reply/application/controller/Test.java
  src/main/java/com/fixplz/reply/application/service/ReplyService.java
  src/main/java/com/fixplz/reply/application/service/Test.java
  src/main/java/com/fixplz/reply/domain/aggregate/entity/Reply.java
  src/main/java/com/fixplz/reply/domain/aggregate/entity/Test.java
  src/main/java/com/fixplz/reply/domain/aggregate/vo/PostNoVO.java
  src/main/java/com/fixplz/reply/domain/aggregate/vo/Test.java
  src/main/java/com/fixplz/reply/domain/repository/ReplyRepository.java
  src/main/java/com/fixplz/reply/domain/repository/Test.java
  src/main/java/com/fixplz/reply/domain/service/ReplyDomainService.java
Labels: ✨ Feature

#9 feature : #8 공감 Entity, 기본 클래스 생성
  src/main/java/com/fixplz/like/application/controller/LikeController.java
  src/main/java/com/fixplz/like/application/dto/request/Test.java
  src/main/java/com/fixplz/like/application/dto/response/Test.java
  src/main/java/com/fixplz/like/application/service/LikeService.java
  src/main/java/com/fixplz/like/domain/aggregate/entity/Like.java
  src/main/java/com/fixplz/like/domain/aggregate/vo/LikeVO.java
  src/main/java/com/fixplz/like/domain/repository/LikeRepository.java
  src/main/java/com/fixplz/like/domain/service/LikeDomainSerivce.java
  src/main/java/com/fixplz/like/infra/service/Test.java
  src/main/java/com/fixplz/reply/domain/service/Test.java
  src/main/java/com/fixplz/sympathy/application/controller/Test.java
  src/main/java/com/fixplz/sympathy/application/dto/request/Test.java
  src/main/java/com/fixplz/sympathy/application/dto/response/Test.java
  src/main/java/com/fixplz/sympathy/application/service/Test.java
  src/main/java/com/fixplz/sympathy/domain/aggregate/entity/Test.java
  src/main/java/com/fixplz/sympathy/domain/aggregate/vo/Test.java
  src/main/java/com/fixplz/sympathy/domain/repository/Test.java
  src/main/java/com/fixplz/sympathy/domain/service/Test.java
  src/main/java/com/fixplz/sympathy/infra/service/Test.java
Labels: ✨ Feature

#10 feature : Member Entity 생성
  build.gradle
  src/main/java/com/fixplz/member/domain/aggregate/entity/Member.java
  src/main/java/com/fixplz/member/domain/aggregate/entity/Role.java
  src/main/java/com/fixplz/member/domain/aggregate/entity/Test.java
Labels: ✨ Feature

#13 [FEATURE] - [STAT] 일일 방문자 통계 조회 기능 구현
  src/main/java/com/fixplz/stat/application/controller/Test.java
  src/main/java/com/fixplz/stat/application/controller/VisitorController.java
  src/main/java/com/fixplz/stat/application/dto/request/VisitorRequest.java
  src/main/java/com/fixplz/stat/application/dto/response/VisitorResponse.java
  src/main/java/com/fixplz/stat/application/service/Test.java
  src/main/java/com/fixplz/stat/application/service/VisitorService.java
  src/main/java/com/fixplz/stat/domain/aggregate/entity/Test.java
  src/main/java/com/fixplz/stat/domain/aggregate/entity/Visitor.java
  src/main/java/com/fixplz/stat/domain/repository/Test.java
  src/main/java/com/fixplz/stat/domain/repository/VisitorDomainRepository.java
  src/main/java/com/fixplz/stat/domain/service/Test.java
  src/main/java/com/fixplz/stat/domain/service/VisitorDomainService.java
  src/main/java/com/fixplz/stat/infra/service/Test.java
  src/main/java/com/fixplz/stat/infrastructure/service/VisitorInfraService.java
  src/main/resources/db/data/data.sql
  src/test/java/com/fixplz/FixplzApplicationTests.java
  src/test/java/com/fixplz/stat/application/service/VisitorServiceTests.java
Labels: 🎯 Test, ✨ Feature, ⚙ Setting

#17 bugfix : Like의 테이블명을 TBL_LIKE로 수정
  src/main/java/com/fixplz/like/domain/aggregate/entity/Like.java
  src/main/java/com/fixplz/like/domain/aggregate/vo/LikeVO.java
Labels: 🐞 BugFix

#22 [Feature] - {CATEGORY} 카테고리 CRUD 기능 구현
  build.gradle
  src/main/java/com/fixplz/category/application/controller/CategoryController.java
  src/main/java/com/fixplz/category/application/controller/Test.java
  src/main/java/com/fixplz/category/application/dto/request/CategoryRequest.java
  src/main/java/com/fixplz/category/application/dto/request/Test.java
  src/main/java/com/fixplz/category/application/dto/response/CategoryResponse.java
  src/main/java/com/fixplz/category/application/dto/response/Test.java
  src/main/java/com/fixplz/category/application/service/CategoryService.java
  src/main/java/com/fixplz/category/application/service/Test.java
  src/main/java/com/fixplz/category/domain/aggregate/entity/Category.java
  src/main/java/com/fixplz/category/domain/aggregate/entity/Test.java
  src/main/java/com/fixplz/category/domain/repository/CategoryRepository.java
  src/main/java/com/fixplz/category/domain/repository/Test.java
  src/main/java/com/fixplz/common/handler/ExceptionResponseHandler.java
  src/main/java/com/fixplz/common/handler/exception/NotFoundException.java
  src/test/java/com/fixplz/category/application/service/CategoryServiceTest.java
Labels: 🎯 Test, ✨ Feature

#25 feature : #24 시설물(facility) entity, 기본 클래스 설정
  src/main/java/com/fixplz/facility/application/controller/FacilityController.java
  src/main/java/com/fixplz/facility/application/dto/request/Test.java
  src/main/java/com/fixplz/facility/application/dto/response/Test.java
  src/main/java/com/fixplz/facility/application/service/FacilityService.java
  src/main/java/com/fixplz/facility/domain/aggregate/entity/Facility.java
  src/main/java/com/fixplz/facility/domain/aggregate/entity/FacilityStatus.java
  src/main/java/com/fixplz/facility/domain/aggregate/vo/FacilityCategoryNoVO.java
  src/main/java/com/fixplz/facility/domain/repository/FacilityRepository.java
  src/main/java/com/fixplz/facility/domain/service/FacilityDomainService.java
  src/main/java/com/fixplz/facility/infra/service/FacilityInfraService.java
Labels: ✨ Feature

#28 feature : #27 시설물 카테고리(facility category) entity, 기본 클래스 설정
  src/main/java/com/fixplz/facilitycategory/application/controller/FacilityCategoryController.java
  src/main/java/com/fixplz/facilitycategory/application/dto/request/Test.java
  src/main/java/com/fixplz/facilitycategory/application/dto/response/Test.java
  src/main/java/com/fixplz/facilitycategory/application/service/Test.java
  src/main/java/com/fixplz/facilitycategory/domain/aggregate/entity/FacilityCategory.java
  src/main/java/com/fixplz/facilitycategory/domain/repository/FacilityCategoryRepository.java
  src/main/java/com/fixplz/facilitycategory/domain/service/FacilityCategoryService.java
  src/main/java/com/fixplz/facilitycategory/infra/service/FacilityCategoryInfraService.java
Labels: ✨ Feature

#30 [Feature] - {Admin} 관리자 도메인 기본 설정
  src/main/java/com/fixplz/Admin/application/controller/AdminController.java
  src/main/java/com/fixplz/Admin/application/dto/request/Test.java
  src/main/java/com/fixplz/Admin/application/dto/response/Test.java
  src/main/java/com/fixplz/Admin/application/service/Test.java
  src/main/java/com/fixplz/Admin/domain/aggregate/entity/Admin.java
  src/main/java/com/fixplz/Admin/domain/repository/AdminRepository.java
  src/main/java/com/fixplz/Admin/domain/service/AdminService.java
  src/main/java/com/fixplz/Admin/infra/service/Test.java
  src/main/java/com/fixplz/member/application/controller/Test.java
  src/main/java/com/fixplz/member/application/dto/request/Test.java
  src/main/java/com/fixplz/member/application/dto/response/Test.java
  src/main/java/com/fixplz/member/application/service/Test.java
  src/main/java/com/fixplz/member/domain/aggregate/entity/Member.java
  src/main/java/com/fixplz/member/domain/aggregate/entity/Role.java
  src/main/java/com/fixplz/member/domain/aggregate/vo/Test.java
  src/main/java/com/fixplz/member/domain/repository/Test.java
  src/main/java/com/fixplz/member/domain/service/Test.java
  src/main/java/com/fixplz/member/infra/service/Test.java
Labels: ✨ Feature
